# name: Cypress Tests

# on: push

# concurrency:
#   group: ${{ github.head_ref || github.ref }}
#   cancel-in-progress: true

# jobs:
#   install-dependencies:
#     name: Install Dependencies
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
#       - name: Install dependencies
#         uses: cypress-io/github-action@v6.4.0
#         with:
#           runTests: false

#   cypress-tests:
#     needs: [install-dependencies]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}

#       - name: Install Specific Chrome Version
#         run: |
#           sudo apt-get install -y wget
#           sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#           sudo apt-get install ./google-chrome-stable_current_amd64.deb

#       - name: End to End Tests
#         uses: cypress-io/github-action@v6.4.0
#         with:
#           build: npm run build
#           start: npm run start
#           wait-on: 'http://localhost:4321'
#           browser: chrome
#           config-file: cypress.config.ts
